repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        'types': [ python ]
        require_serial: true
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        files: ^app/
        entry: mypy --show-error-codes --no-warn-unused-ignores --follow-imports silent app
        pass_filenames: false
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy-stubs'
          - 'types-python-slugify'
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: flake8
        language: python
        types: [ python ]
        require_serial: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit excluding the test directory
        language_version: python3
        exclude: ^tests/
      - id: bandit
        name: bandit only the test directory
        language_version: python3
        files: ^tests/
        args:
          - --skip
          - "B101,B105,B311"
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-yaml
