version: "3.8"

services:
  app:
    build: .
    ports:
      - 80:80
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=changethis
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  app-db-data:
